# Generated by Django 3.1.5 on 2021-05-05 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
