# Generated by Django 3.1.5 on 2021-05-05 22:56

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='min_deposit',
            field=models.CharField(max_length=1000,default='You can withdraw your funds only on external address, which is registered and verified with your account. To verify your (external) address with your account, you need to make a deposit from this address. Deposited amount will be added to your current balance amount and will be available for withdrawal at any time immediately. More information you will find on Deposit area in your profile. Minimal amount of the deposit is 0.005 BTC'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=app.models.user_directory_path),
        ),
    ]
