# Generated by Django 3.1.5 on 2021-05-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210506_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('name', models.TextField()),
                ('title', models.TextField()),
                ('status', models.BooleanField()),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('worker_id', models.TextField()),
                ('balance', models.IntegerField()),
                ('currency', models.TextField()),
                ('referral', models.IntegerField()),
                ('referrals', models.IntegerField()),
                ('ban_status', models.IntegerField()),
                ('warnings', models.IntegerField()),
                ('status', models.TextField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='WorkerWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('address', models.TextField()),
                ('wif', models.TextField()),
                ('seed', models.TextField()),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'wallets',
            },
        ),
    ]
