# Generated by Django 3.1.5 on 2021-05-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_trader_referral_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='worker_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
