# Generated by Django 3.1.5 on 2021-05-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_trader_worker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='referral_bonus',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
