# Generated by Django 3.1.5 on 2021-05-19 08:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210519_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='terms_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
