# Generated by Django 3.1.5 on 2021-05-19 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210519_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='is_banned',
        ),
    ]
