# Generated by Django 3.1.5 on 2021-05-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210525_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='bot_token',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
