# Generated by Django 3.1.5 on 2021-05-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_trader_bot_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='chat_token',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
