# Generated by Django 3.1.5 on 2021-05-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='wallet',
            field=models.CharField(max_length=500),
        ),
    ]
