# Generated by Django 3.1.5 on 2021-05-26 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_notification_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='app.trader'),
        ),
    ]
