# Generated by Django 3.1.5 on 2021-05-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20210526_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit',
            name='date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
