# Generated by Django 3.1.5 on 2021-05-27 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20210527_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.trader'),
        ),
    ]
