# Generated by Django 3.1.5 on 2021-05-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_profit_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='password',
        ),
        migrations.AddField(
            model_name='trader',
            name='telegram_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
