# Generated by Django 3.1.5 on 2021-05-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20210527_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
