# Generated by Django 3.1.5 on 2021-06-01 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_trader_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_users', models.IntegerField()),
                ('regular_users', models.IntegerField()),
                ('transaction', models.IntegerField()),
                ('visits', models.IntegerField()),
                ('processing_time', models.IntegerField()),
                ('top_pair', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='referral',
            name='referred',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='app.trader'),
        ),
        migrations.AlterUniqueTogether(
            name='referral',
            unique_together={('referred',)},
        ),
    ]
