# Generated by Django 3.2.3 on 2021-08-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='min_deposit',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
